### ISSUE TITLE
Missing game

### ISSUE THREAD

**Issue by barthisius** [FriendsOfGalaxy/galaxy-integration-paradox#4]
**Describe the bug**
I have Stellaris on Paradox, and it had been showing up in Galaxy as expected, but about a week or so ago it disappeared. (It stopped showing up when I disconnected and reconnected the integration, to deal with some connection issues I'm having as described in #3. If the issues are related they could be merged, but since this is a more recent bug, it seemed distinct). As suggested in the Common Problems page, I synced the integrations in Galaxy and checked the log file, and it's sending a blank list for "owned_games". Stellaris is the only game I have, so I don't know if it's specific to Stellaris or if all games would be missing. And in case it's relevant: I don't currently have it installed through Paradox, and I also own the game on my synced Steam account.

**To Reproduce**
I'm not sure what changed to make it stop working, or if others are having similar problems, so I don't know what would need to be done to reproduce it. If there's anything I can do to help troubleshoot it, please let me know.

**Expected behavior**
I expected Stellaris to show up in my games again after re-connecting the Paradox integration. It seems strange to have suddenly stopped.

**Attached logs**
[plugin-paradox-bfa5a6c9-r0c3-5g28-b921-f4cd75d4999a.log](https://github.com/FriendsOfGalaxy/galaxy-integration-paradox/files/3942819/plugin-paradox-bfa5a6c9-r0c3-5g28-b921-f4cd75d4999a.log)

**Comment by dumstarboi** [comment]
Looking through my log file more carefully and the changes made in commit 299bc981, it looks like it's getting Stellaris as owned in the response from Paradox, but it's being filtered out by the new check in backend.py for `"paradox builds" in game['platforms']`, because the response shows the platforms as being only `['steam', 'linux', 'mac', 'windows']`.
Recently, I purchased a new DLC from Paradox and it _does_ have `"paradox builds"` listed. So my gut suggests this only shows up for games purchased directly through Paradox, not those purchased on Steam. But that's just a guess. (If someone else has Stellaris maybe they can confirm?)

If it's helpful, I'd be willing to take a shot at trying to work out a fix for this (though I can't promise I can figure it out). But I don't know much about the inner workings of Galaxy integrations or the Paradox API, so is there some documentation I could reference for that? And what was the reason the check for `"paradox builds"` was added in the first place?

**Comment by FriendsOfGalaxy** [comment]
Hi, plugin currently do not support games purchased by steam. Is your paradox launcher able to launch it? Did you connected your steam and paradox accounts? https://www.paradoxplaza.com/steamactiviation.html 

If you would like to contribute, there is API documentation: https://github.com/gogcom/galaxy-integrations-python-api - some devs can help on discord cafe chat https://discord.gg/372vxnZ
As far as Paradox API is concerned, I do not know any public documentation. The only thing I've found are endpoints used by https://accounts.paradoxplaza.com/games 
You can preview with debug tools.
![cd9aa8822bb708855104f07b64dfc00c](https://user-images.githubusercontent.com/48480506/70912810-08aa4500-2015-11ea-8979-fdca8cb07731.png)

I couldn't find what their desktop launcher is using.

**Comment by dumstarboi** [comment]
Oh okay, it's good to know it's not just a bug. It does work through the paradox launcher though. (and my steam & paradox accounts are connected)

But wow thanks for all the info! That's everything I was hoping for.

I trawled through the responses used by [https://accounts.paradoxplaza.com/games](https://accounts.paradoxplaza.com/games) to see how they manage it, since Stellaris shows up on this page as well. In the `products` response it doesn't seem to have anything to distinguish Stellaris (as purchased on Steam) from other games from the connected account that _don't_ work through the paradox launcher. So I think the key is the `skus` request, where `"paradoxLauncher"` is a platform for Stellaris, but not for the other games that don't work.

I should have time after work to put something together to try.

**Comment by FriendsOfGalaxy** [comment]
@barthisius thanks for contribution! I'm marking as fixed.
